<template>
  <el-container>
    <div class="static">
      <aside class="static-aside">
        <div class="static-aside__title">
          Security
        </div>
      </aside>
      <section class="static-content">
        <h1>Security and confidentiality of data</h1>
        <p>The MTender Operator is committed to protecting the security of information and privacy of MTender users and visitors.  The MTender operates security measures to protect against the loss, misuse and alteration of information under the control of the Operator of the MTender and the MTender networking electronic procurement platforms. Protection of bid information, confidential information and personal data from unauthorized access against leakage, destruction, blocking or violation to the integrity of data is ensured by the MTender in accordance to security requirements for the MTender Operator and the MTender networking electronic procurement platforms prescribed in the order of the Ministry of Finance.</p>
        <p>Operations and activities carried out in the MTender by all Registered Users are recorded in log files generated by the systems where the day and time of each access and activity is indicated. The data recorded in the log files of the MTender shall be reported in real time to the government service MLog to ensure accuracy and confidentiality of data. The MTender record on the MLog constitutes a complete and exclusive evidence between the Clients, the Economic Operators and the relevant enforcement agencies of the Republic of Moldova about the content and the timing of electronic documents exchanged and communications sent, such as, but not limited to, requests to participate and bids submitted, contract notices published as well evaluation decisions completed by the Client. </p>
        <p>The MTender networking platforms ensure confidentiality, access control and validation of information provided by the buyers and the economic operators during registration for identification and authentication purposes as well as the integrity and availability of all registration information that is processed for the MTender.</p>
      </section>
    </div>
  </el-container>
</template>

<script>
  export default {
    name: "SecurityAndConfidentiality"
  };
</script>
