export const FETCH_ENTITY_LIST = "FETCH_ENTITY_LIST";

export const FETCH_CURRENT_BUDGET_INFO = "FETCH_CURRENT_BUDGET_INFO";
export const FETCH_CURRENT_TENDER_INFO = "FETCH_CURRENT_TENDER_INFO";
export const FETCH_CURRENT_CONTRACT_INFO = "FETCH_CURRENT_CONTRACT_INFO";

export const FETCH_CPV_CODES = "FETCH_CPV_CODES";

export const FETCH_REGIONS = "FETCH_REGIONS";
