export const SET_ENTITY_LOADED = "SET_ENTITY_LOADED";

export const SET_ENTITY_LIST = "SET_ENTITY_LIST";
export const SET_ENTITY_PAGINATION_INFO = "SET_ENTITY_PAGINATION_INFO";
export const SET_ENTITY_SEARCH_PARAMS = "SET_ENTITY_SEARCH_PARAMS";

export const SET_CURRENT_BUDGET_INFO = "SET_CURRENT_BUDGET_INFO";
export const SET_CURRENT_TENDER_INFO = "SET_CURRENT_TENDER_INFO";

export const SET_CPV_CODES = "SET_CPV_CODES";
export const SET_REGIONS = "SET_REGIONS";

export const SET_INITIAL_SEARCH_PARAMS = "SET_INITIAL_SEARCH_PARAMS";
