export const SET_ENTITY_LIST = "SET_ENTITY_LIST";
export const SET_ENTITY_PAGINATION_INFO = "SET_ENTITY_PAGINATION_INFO";
export const SET_ENTITY_SEARCH_PARAMS = "SET_ENTITY_SEARCH_PARAMS";

export const SET_DIRECTORY = "SET_DIRECTORY";
